name: pmi_jateng
description: "PMI"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  google_sign_in: ^6.2.1
  animated_bottom_navigation_bar: 1.3.3
  convex_bottom_bar: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  http: ^1.2.1
  flutter_svg: ^1.0.3
  carousel_slider: ^4.0.0
  flutter_image_slideshow: ^0.1.6
  build_runner: ^2.4.11
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  get: ^4.6.6
  shared_preferences: ^2.2.3
  webview_flutter: ^4.8.0
  dio: ^5.5.0+1
  get_storage: ^2.1.1
  image_picker: ^0.8.4+4
  intl: ^0.19.0
  csrf: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1
  freezed: ^2.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/font/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-ExtraBold.ttf # Sesuaikan dengan nama file sebenarnya
          weight: 800
        - asset: assets/font/Poppins-ExtraBold.ttf # Sesuaikan dengan nama file sebenarnya
          weight: 800
        - asset: assets/font/Poppins-Bold.ttf # Sesuaikan dengan nama file sebenarnya
          weight: 700
        - asset: assets/font/Poppins-SemiBold.ttf # Sesuaikan dengan nama file sebenarnya
          weight: 600
        - asset: assets/font/Poppins-Medium.ttf # Sesuaikan dengan nama file sebenarnya
          weight: 500
        - asset: assets/font/Poppins-Regular.ttf # Sesuaikan dengan nama file sebenarnya
          weight: 400
        - asset: assets/font/Poppins-Light.ttf
          weight: 300

    - family: JosefinSans
      fonts:
        - asset: assets/font/JosefinSans-Bold.ttf
          weight: 700
        - asset: assets/font/JosefinSans-SemiBold.ttf
          weight: 600
        - asset: assets/font/JosefinSans-Medium.ttf
          weight: 500
        - asset: assets/font/JosefinSans-Regular.ttf
          weight: 400
        - asset: assets/font/JosefinSans-Light.ttf
          weight: 300

    - family: Freehand
      fonts:
        - asset: assets/font/Freehand-Regular.ttf
          weight: 400

    - family: Judson
      fonts:
        - asset: assets/font/Judson-Bold.ttf
          weight: 400
