// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGUWDcFy-GaFmlUuA3zH4pJByDxGpkghw',
    appId: '1:445860739698:android:d2a245064e83ad790020eb',
    messagingSenderId: '445860739698',
    projectId: 'nuraga-862b9',
    databaseURL: 'https://nuraga-862b9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nuraga-862b9.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeYyOyeHz-1XvsA79h9It2FFIpJWRLw9Y',
    appId: '1:445860739698:web:ff39f003b13403810020eb',
    messagingSenderId: '445860739698',
    projectId: 'nuraga-862b9',
    authDomain: 'nuraga-862b9.firebaseapp.com',
    databaseURL: 'https://nuraga-862b9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nuraga-862b9.appspot.com',
    measurementId: 'G-DPL06XBWF5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeYyOyeHz-1XvsA79h9It2FFIpJWRLw9Y',
    appId: '1:445860739698:web:f46c199517ab82ea0020eb',
    messagingSenderId: '445860739698',
    projectId: 'nuraga-862b9',
    authDomain: 'nuraga-862b9.firebaseapp.com',
    databaseURL: 'https://nuraga-862b9-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'nuraga-862b9.appspot.com',
    measurementId: 'G-74GMDG22SZ',
  );

}